### ISSUE TITLE
Criar manifestos do Kubernetes

### ISSUE THREAD

**Issue by olegon** [pabloldias/soat1-grupo18#30]
# Escopo

1. Deployment da aplicação com pelo menos 2 Pods;
2. Service Load Balancer do tipo ALB ou NLB;
3. Configuração de acesso aos serviços da AWS parametrizados via Secrets;

**Comment by olegon** [comment]
Sobre esse item 1, será que seria um Pod para a aplicação e outro para o banco de dados?

**Comment by olegon** [comment]
Sobre esse item 2, será que é apenas um Service do tipo LoadBalancer que se integra com um Elastic Load Balancer?

**Comment by olegon** [comment]
Sobre esse item 3, será que são segredos para usar imagens do ECR ou segredos com as credenciais do banco de dados?

**Comment by olegon** [comment]
Essa parte que Kubernetes gerou dúvidas para muitas pessoas, então existe uma *thread* no Discord com várias perguntas e respostas: https://discord.com/channels/1065992165232214066/1134870064122830999/1134870064122830999

**Comment by olegon** [comment]
Sobre a parte do LoadBalancer, essa questão do Elastis Load Balancer, parece que só precisamos ficar atentos com uma *annotation* usada pela AWS. Vou confirmar se é isso mesmo.

**Comment by pabloldias** [comment]
Segue dúvida no Discord que pode ajudar nos itens 2 e 3:

https://discord.com/channels/1065992165232214066/1140610208289280066/1140610208289280066
